export const DATA_LIST_REQUEST = 'DATA_LIST_REQUEST';
export const DATA_LIST_SUCCESS = 'DATA_LIST_SUCCESS';
export const DATA_LIST_FAIL = 'DATA_LIST_FAIL';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';